apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: prod-python-helloworld
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: helloworld
        image: docker.io/gejun/helloworld:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
          name: webapp
