apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: prod-python-helloworld
spec:
  type: LoadBalancer
  ports:
  - name: "webapp-service"
    port: 80
  selector:
    app: webapp
    